### ISSUE TITLE
change the name raflex

### ISSUE THREAD

**Issue by boralp** [argyleink/ragrid#1]
new display grid will be popular soon, and it may make confusions

**Comment by argyleink** [comment]
totally agree that there could be confusion now that CSS grid is available in modern browsers, especially since this library is definitely not a replacement for CSS grid. also agree that having flex in the name would help people know this is a flexbox grid. BUT, CSS grid is an extrinsic methodology, and this is intrinsic. if anything, the name i change this to need to have something more to do with alignment, distribution and intrinsics. 

what do you think about Intrinsick lol, it's so sick and intrinsic, or flexalign... naming things is hard.

**Comment by boralp** [comment]
Thank you, you got my point so no worries maybe an upgraded line of description or in the future css grid support.
